Repository adjoint-io/bulletproofs, pull requests merged in 2019-09, with the labels that each got.

#19 Upgrade to latest galois-field and elliptic-curve deps
  .gitignore
  Bulletproofs/ArithmeticCircuit/Internal.hs
  Bulletproofs/ArithmeticCircuit/Prover.hs
  Bulletproofs/ArithmeticCircuit/Verifier.hs
  Bulletproofs/Curve.hs
  Bulletproofs/Fq.hs
  Bulletproofs/InnerProductProof/Internal.hs
  Bulletproofs/InnerProductProof/Prover.hs
  Bulletproofs/InnerProductProof/Verifier.hs
  Bulletproofs/MultiRangeProof/Prover.hs
  Bulletproofs/MultiRangeProof/Verifier.hs
  Bulletproofs/RangeProof/Internal.hs
  Bulletproofs/RangeProof/Prover.hs
  Bulletproofs/RangeProof/Verifier.hs
  Bulletproofs/Utils.hs
  bench/Main.hs
  package.yaml
  stack.yaml
  stack.yaml.lock
  tests/TestArithCircuitProtocol.hs
  tests/TestField.hs
  tests/TestProtocol.hs
Labels: ready-to-review

#21 Update poly dependency
  stack.yaml
Labels: wip

#22 Add elliptic-curve dependency
  Bulletproofs/ArithmeticCircuit/Internal.hs
  Bulletproofs/ArithmeticCircuit/Prover.hs
  Bulletproofs/ArithmeticCircuit/Verifier.hs
  Bulletproofs/InnerProductProof/Prover.hs
  Bulletproofs/InnerProductProof/Verifier.hs
  Bulletproofs/MultiRangeProof/Prover.hs
  Bulletproofs/MultiRangeProof/Verifier.hs
  Bulletproofs/RangeProof/Internal.hs
  Bulletproofs/Utils.hs
  ChangeLog.md
  README.md
  bench/Bench/ArithCircuit.hs
  bench/Bench/RangeProof.hs
  bench/Main.hs
  example/Example/ArithmeticCircuit.hs
  example/Example/RangeProof.hs
  example/Main.hs
  package.yaml
  stack.yaml
  stack.yaml.lock
  test/Main.hs
  test/Test/Common.hs
  test/Test/Field.hs
  test/Test/Protocol/ArithCircuit.hs
  test/Test/Protocol/RangeProof.hs
Labels: ready-to-merge
